name: Default

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.101'
      - id: build_asset
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          Write-Host "::set-ouput name=file_name::$((Get-ChildItem .\dist -File).Name)"
      - id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ""
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/${{ steps.build_asset.outputs.file_name }}
          asset_name: ${{ steps.build_asset.outputs.file_name }}
          asset_content_type: application/zip
